package src 
{
	
	/**
	 * Required to have the compiler include these items in the final build
	 * @author Giuliano
	 */
	public class ImportObjects 
	{
		
		public function ImportObjects() 
		{
			//Icons
			ICON_WORLD;
			ICON_CROP;
			ICON_BATTLE;
			ICON_CLOCK;
			ICON_IRON;
			ICON_GOLD;
			ICON_WOOD;
			ICON_LABOR;
			ICON_ALERT;
			ICON_MESSAGE;
			
			//Passive Action Icons
			PASSIVE_ATTACKING;
			PASSIVE_DEFENDING;
			PASSIVE_RETREATING;
			
			//Tiles
			DOT_SPRITE;
			DOT_SPRITE_ORANGE;
			DOT_SPRITE_BLACK;
			DOT_SPRITE_WHITE;
			MASK_TILE;
			TILE_MINI;
			
			//Walls
			WALL_NE_0;
			WALL_NW_0;
			WALL_SE_0;
			WALL_SW_0;
			WALL_N_0;
			WALL_S_0;
			WALL_W_0;
			WALL_E_0;
			WALL_NE_1;
			WALL_NW_1;
			WALL_SE_1;
			WALL_SW_1;
			WALL_N_1;
			WALL_S_1;
			WALL_W_1;
			WALL_E_1;		
			WALL_O1;
			WALL_O2;
			WALL_O3;
			WALL_O4;
			
			//Forest
			DEFAULT_FOREST;
			
			//Troops
			DEFAULT_TROOP;			
			
			//UNITS
			DEFAULT_UNIT;
			
			//Dialog
			MOVEMENT_DIALOG_BG;
			
			//Structures
			ARMORY_STRUCTURE;
			BARRACK_STRUCTURE;
			DEFAULT_BUILDING;
			DEFAULT_BUILDING_ANIM;
			DEFAULT_STRUCTURE_SIMPLE;
			DEFAULT_STRUCTURE_COMPLEX;
			EMBASSY_STRUCTURE;
			FOUNDRY_STRUCTURE;
			STABLE_STRUCTURE;
			FARM_STRUCTURE;
			BLACKSMITH_STRUCTURE
			MARKET_STRUCTURE;
			REFINERY_STRUCTURE;
			STABLE_STRUCTURE;
			TOWER_STRUCTURE;
			TOWNCENTER_STRUCTURE;
			TRADING_POST_STRUCTURE;
			UNIVERSITY_STRUCTURE;
			LUMBERMILL_STRUCTURE
			WORKSHOP_STRUCTURE;			
			TRAINING_GROUND_STRUCTURE;
			CANNON_TOWER_STRUCTURE;
			BLACKSMITH_STRUCTURE;
			BASEMENT_STRUCTURE;
			FOREST_CAMP_STRUCTURE;
			
			//Object Info Sidebar Buttons
			DEFAULT_BUILD_ROAD_BUTTON;
			DEFAULT_ROAD_DESTROY_BUTTON;
			DEFAULT_LABOR_MOVE_BUTTON;
			DEFAULT_FOREST_CAMP_REMOVE_BUTTON;
			DEFAULT_BUILD_BUTTON;
			DEFAULT_CHANGE_BUTTON;
			DEFAULT_ACTION_BUTTON;
			DEFAULT_MARKET_BUY_BUTTON;
			DEFAULT_MARKET_SELL_BUTTON;
			DEFAULT_TECHNOLOGY_BUTTON;
			DEFAULT_TRAIN_BUTTON;
			DEFAULT_STRUCTURE_UPGRADE_BUTTON;
			DEFAULT_UNIT_UPGRADE_BUTTON;			
		}
		
	}
	
}