<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';

include_once $GLOBALS['THRIFT_ROOT'].'/packages/service/service_types.php';

interface NotificationIf {
  public function NewMessage($playerUnreadCount);
  public function NewTribeForumPost($tribeId, $unreadCount);
  public function NewBattleReport($playerUnreadCount);
}

$GLOBALS['THRIFT_AUTOLOAD']['notificationclient'] = 'service/service.Notification.client.php';
// HELPER FUNCTIONS AND STRUCTURES

?>
