<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


$GLOBALS['THRIFT_AUTOLOAD']['playerunreadcount'] = 'service/service.PlayerUnreadCount.php';
$GLOBALS['THRIFT_AUTOLOAD']['notification_newmessage_args'] = 'service/service.Notification_NewMessage_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['notification_newmessage_result'] = 'service/service.Notification_NewMessage_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['notification_newtribeforumpost_args'] = 'service/service.Notification_NewTribeForumPost_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['notification_newtribeforumpost_result'] = 'service/service.Notification_NewTribeForumPost_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['notification_newbattlereport_args'] = 'service/service.Notification_NewBattleReport_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['notification_newbattlereport_result'] = 'service/service.Notification_NewBattleReport_result.php';
?>
